language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
env:
  global:
    - MAVEN_OPTS="-Xmx3072m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
script: mvn install -Ptravis && mvn javadoc:javadoc
after_success:
  - bash <(curl -s https://codecov.io/bash)