language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8

install: travis_wait mvn -q install -PreducedMemory -Dfindbugs.skip=true
script: travis_wait mvn findbugs:findbugs -o && mvn javadoc:javadoc -o
